on:
  push:
    branches:
      - master
      - workflow
jobs:
  test:
    runs-on: ubuntu-latest
    name: Build and Test
    steps:
      - uses: actions/checkout@v3
      - uses: mlugg/setup-zig@v2
      - name: Install Wine
        run: |
          sudo dpkg --add-architecture i386
          sudo apt update
          sudo apt install -y wine64 wine32:i386
          wineboot
      - name: Run Tests
        run: |
          zig build build-tests
          wineconsole ./zig-out/bin/test.exe
