on:
  push:
    branches:
      - master
      - workflow
jobs:
  test:
    runs-on: ubuntu-latest
    name: Build and Test
    steps:
      - uses: actions/checkout@v3
      - uses: mlugg/setup-zig@v2
      - name: Install Wine
        run: |
          sudo apt update
          sudo apt install -y wine64
          zig build test
