on:
  push:
    branches:
      - master
jobs:
  test:
    runs-on: ubuntu-latest
    name: Build and Test
    steps:
      - uses: actions/checkout@v3
      - uses: rishabhc32/apt-package-cache@v1.0.1
        with:
          packages: wine
      - uses: mlugg/setup-zig@v2
      - name: Install Wine
        run: |
          # sudo dpkg --add-architecture i386
          # sudo apt update
          # sudo apt install -y wine64 wine32:i386
          wineboot
      - name: Run Tests
        run: zig build test -fwine
      - name: Compile all examples
        run: |
          for example in "./examples/*.zig"; do
            filename=$(basename $file)
            zig build example.${filename%.*}
          done
